"""Add previous_passwords column as nullable

Revision ID: c06ee862357a
Revises: dbed7f052fc4
Create Date: 2025-05-13 08:35:12.952114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06ee862357a'
down_revision = 'dbed7f052fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_passwords', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_previous_passwords'), ['previous_passwords'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_previous_passwords'))
        batch_op.drop_column('previous_passwords')

    # ### end Alembic commands ###
