"""empty message

Revision ID: ee47efaaf63b
Revises: 9d769080e7f3
Create Date: 2025-04-04 19:54:41.543848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee47efaaf63b'
down_revision = '9d769080e7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.drop_column('password_hashing')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hashing', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
